name: builds

on: [push]

jobs:
  build-old:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        node: [16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
      - run: npm i -g pnpm
      - run: pnpm i --frozen-lockfile
        env:
          npm_config_build_from_source: true
      - run: pnpm lint
      - run: pnpm tsd
      - run: pnpm test
      - run: pnpm package
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-${{ matrix.node }}-binary
          path: 'build/**/*.tar.gz'
  deploy:
    runs-on: ubuntu-18.04
    needs: [build-old]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - uses: actions/download-artifact@v2
        with:
          path: build
      - id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - uses: eine/tip@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.vars.outputs.tag }}
          files: |
            ./build/*/stage/lipt-rb/libxmljs2-ctf-xxe-vuln/releases/download/*/*
